SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

-- TRAS REGISTROS NÃO DUPLICADOS USANDO COMBINACAO DE EMBALAGEM E TAMNHO
SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

-- TRAS REGISTROS NÃO DUPLICADOS USANDO COMBINACAO DE EMBALAGEM E TAMNHO COM FILTRO SABOR LARANJA
SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Laranja'

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]

select top 3 * from [TABELA DE PRODUTOS]

select * from [TABELA DE CLIENTES] order by NOME desc